# Generated by Django 4.1.5 on 2023-01-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_product_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
